[web]
web_server_public_ip ansible_host=16.112.192.28

[db]
db_server_private_ip ansible_host=10.0.2.48

[db:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@16.112.192.28 -i /home/ubuntu/demo.pem"'